const pairIdMap = {
    'EURUSD': '1',
    'USDJPY': '2',
    'GBPUSD': '3',
    'USDCHF': '4',
    'AUDUSD': '5',
    'USDCAD': '6',
    'NZDUSD': '7',
    'EURGBP': '8',
    'EURAUD': '9',
    'EURCAD': '10',
    'EURCHF': '11',
    'EURJPY': '12',
    'GBPJPY': '13',
    'CHFJPY': '14',
    'GBPAUD': '15',
    'GBPCAD': '16',
    'GBPCHF': '17',
    'AUDJPY': '18',
    'AUDCAD': '19',
    'AUDCHF': '20',
    'CADJPY': '21',
    'NZDJPY': '22',
    'AUDNZD': '23',
    'CADCHF': '24',
    "GBPUSD": '3',
    "USDCHF": '4',
    "AUDUSD": '5',
    "USDCAD": '6',
    "NZDUSD": '7',
    "EURGBP": '8',
    "EURAUD": '9',
    "EURNZD": "25",
    "NZDCAD":"26",
    "NZDCHF":"27",
    "GBPNZD":"28",
   };



  module.exports = {
    pairIdMap,
  };